<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CiriCiri;

class CiriCiriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ciriCiri = [
            ['kode' => 'L001', 'deskripsi' => 'Suka bercerita.'],
            ['kode' => 'L002', 'deskripsi' => 'Memiliki ingatan yang baik untuk hal-hal yang sepele.'],
            ['kode' => 'L003', 'deskripsi' => 'Menyukai permainan kata-kata.'],
            ['kode' => 'L004', 'deskripsi' => 'Hobi membaca buku.'],
            ['kode' => 'L005', 'deskripsi' => 'Seorang pembicara yang baik.'],
            ['kode' => 'L006', 'deskripsi' => 'Menyukai pelajaran bahasa daripada matematika dan ilmu alam.'],
            ['kode' => 'L007', 'deskripsi' => 'Senang membayangkan dan menulis ide-ide yang ada di otak.'],
            ['kode' => 'L008', 'deskripsi' => 'Memiliki kosakata yang cukup banyak sehingga tidak ada hambatan atau kesulitan dalam berkomunikasi dengan berbagai kalangan.'],
            ['kode' => 'L009', 'deskripsi' => 'Senang menulis karangan, atau segala hal yang berbentuk tulisan.'],
            ['kode' => 'L010', 'deskripsi' => 'Lebih memilih untuk menulis dalam presentasi kelompok.'],
            ['kode' => 'L011', 'deskripsi' => 'Dapat menggunakan banyak kata-kata yang berbeda untuk mengekspresikan diri.'],
            ['kode' => 'L012', 'deskripsi' => 'Menyukai perdebatan dan diskusi.'],
            ['kode' => 'L013', 'deskripsi' => 'Sangat menyukai pelajaran matematika.'],
            ['kode' => 'L014', 'deskripsi' => 'Menyukai permainan yang menggunakan logika, seperti teka-teki angka.'],
            ['kode' => 'L015', 'deskripsi' => 'Dapat memecahkan soal-soal hitungan.'],
            ['kode' => 'L016', 'deskripsi' => 'Jika harus mengingat sesuatu, cenderung menempatkan setiap kejadian dalam urutan yang logis.'],
            ['kode' => 'L017', 'deskripsi' => 'Senang mencari tahu bagaimana cara kerja setiap benda.'],
            ['kode' => 'L018', 'deskripsi' => 'Menyukai komputer dan berbagai permainan angka-angka.'],
            ['kode' => 'L019', 'deskripsi' => 'Menyukai permainan catur, sudoku, atau monopoli.'],
            ['kode' => 'L020', 'deskripsi' => 'Dapat menghitung angka di luar kepala dengan mudah.'],
            ['kode' => 'L021', 'deskripsi' => 'Jika sesuatu rusak dan tidak berfungsi, akan melihat bagian-bagiannya dan mencari tahu bagaimana cara kerjanya.'],
            ['kode' => 'L022', 'deskripsi' => 'Suka berpikir melalui masalah dengan hati-hati, mempertimbangkan segala konsekuensinya.'],
            ['kode' => 'L023', 'deskripsi' => 'Senang menonton film atau membaca buku yang melibatkan berpikir logis seperti buku / film detektif.'],
            ['kode' => 'L024', 'deskripsi' => 'Senang membuat eksperimen sederhana.'],
            ['kode' => 'L025', 'deskripsi' => 'Lebih memilih peta daripada petunjuk tertulis dalam mencari sebuah alamat.'],
            ['kode' => 'L026', 'deskripsi' => 'Gemar dan mampu mengerjakan teka-teki menyusun potongan gambar, labirin dan teka-teki visual lainnya.'],
            ['kode' => 'L027', 'deskripsi' => 'Hobi dalam bidang fotografi.'],
            ['kode' => 'L028', 'deskripsi' => 'Senang menggambar dan menciptakan sesuatu.'],
            ['kode' => 'L029', 'deskripsi' => 'Menyukai pelajaran geografi daripada matematika.'],
            ['kode' => 'L030', 'deskripsi' => 'Senang membuat coretan-coretan di kertas.'],
            ['kode' => 'L031', 'deskripsi' => 'Ketika membaca majalah, lebih suka melihat gambar-gambarnya daripada membaca teksnya.'],
            ['kode' => 'L032', 'deskripsi' => 'Mahir membangun konstruksi tiga dimensi seperti lego.'],
            ['kode' => 'L033', 'deskripsi' => 'Lebih mudah belajar dengan gambar daripada dengan teks.'],
            ['kode' => 'L034', 'deskripsi' => 'Menyukai pelajaran seni rupa.'],
            ['kode' => 'L035', 'deskripsi' => 'Menata ulang ruangan adalah hal menyenangkan.'],
            ['kode' => 'L036', 'deskripsi' => 'Dapat dengan mudah membayangkan bagaimana penampakan suatu benda dilihat dari berbagai sisi.'],
            ['kode' => 'L037', 'deskripsi' => 'Senang mendengarkan musik dan radio.'],
            ['kode' => 'L038', 'deskripsi' => 'Cenderung bersenandung ketika sedang melakukan aktivitas.'],
            ['kode' => 'L039', 'deskripsi' => 'Memiliki suara yang merdu.'],
            ['kode' => 'L040', 'deskripsi' => 'Bisa memainkan salah satu alat musik dengan baik.'],
            ['kode' => 'L041', 'deskripsi' => 'Suka mendengarkan musik sambil belajar atau sambil membaca buku.'],
            ['kode' => 'L042', 'deskripsi' => 'Jika harus mengingat sesuatu, mencoba untuk membuat irama tentang hal tersebut.'],
            ['kode' => 'L043', 'deskripsi' => 'Menikmati berbagai macam gaya musik.'],
            ['kode' => 'L044', 'deskripsi' => 'Apabila mendengarkan suatu karya musik satu atau dua kali, dapat menyanyikannya kembali dengan cukup baik.'],
            ['kode' => 'L045', 'deskripsi' => 'Jika sesuatu rusak dan tidak berfungsi, cenderung mengetuk-ngetuk jari membentuk suatu irama sambil menari / jatuh keluar.'],
            ['kode' => 'L046', 'deskripsi' => 'Lebih bersemangat ketika musik dimainkan.'],
            ['kode' => 'L047', 'deskripsi' => 'Tahu apabila ada nada musik yang sumbang.'],
            ['kode' => 'L048', 'deskripsi' => 'Kadangkala berjalan kaki sambil melantunkan lagu.'],
            ['kode' => 'L049', 'deskripsi' => 'Olahraga merupakan suatu hobi.'],
            ['kode' => 'L050', 'deskripsi' => 'Menyukai kegiatan-kegiatan seperti menjahit dan membuat bentuk-bentuk.'],
            ['kode' => 'L051', 'deskripsi' => 'Penting untuk menyentuh benda yang baru ditemukan untuk melengkapi informasi mengenai benda tersebut.'],
            ['kode' => 'L052', 'deskripsi' => 'Tidak dapat duduk diam dalam waktu yang lama.'],
            ['kode' => 'L053', 'deskripsi' => 'Selalu menggunakan gerak tangan atau bahasa tubuh lain ketika berbicara dengan orang lain.'],
            ['kode' => 'L054', 'deskripsi' => 'Pernah mempunyai prestasi yanng cukup menonjol di salah satu atau lebih cabang olahraga.'],
            ['kode' => 'L055', 'deskripsi' => 'Menikmati kegiatan yang menantang bahaya atau pengalaman fisik yang menegangkan.'],
            ['kode' => 'L056', 'deskripsi' => 'Suka pekerjaan yang melibatkan keterampilan tangan.'],
            ['kode' => 'L057', 'deskripsi' => 'Jika sesuatu rusak dan tidak berfungsi, cenderung memisahkan setiap bagian lalu menggabungkannya kembali.'],
            ['kode' => 'L058', 'deskripsi' => 'Harus mempraktikkan sesuatu keterampilan yang baru, tidak sekedar membaca atau melihat.'],
            ['kode' => 'L059', 'deskripsi' => 'Gagasan terbaik biasanya muncul ketika jalan-jalan atau jogging atau saat terlibat kegiatan fisik lainnya.'],
            ['kode' => 'L060', 'deskripsi' => 'Ikut sekurang-kurangnya satu kegiatan olahraga atau kegiatan fisik secara teratur.'],
            ['kode' => 'L061', 'deskripsi' => 'Mampu bergaul baik dengan orang lain.'],
            ['kode' => 'L062', 'deskripsi' => 'Senang berkumpul dan berorganisasi.'],
            ['kode' => 'L063', 'deskripsi' => 'Mempunyai beberapa teman dekat.'],
            ['kode' => 'L064', 'deskripsi' => 'Suka untuk mengajari orang lain tentang hal-hal yang dipelajari.'],
            ['kode' => 'L065', 'deskripsi' => 'Senang bekerja sama dalam kelompok.'],
            ['kode' => 'L066', 'deskripsi' => 'Sering didatangi orang untuk dimintai nasehat atau saran, baik di sekolah maupun di lingkungan tempat tinggal.'],
            ['kode' => 'L067', 'deskripsi' => 'Jika harus mengingat sesuatu akan meminta seseorang untuk menguji.'],
            ['kode' => 'L068', 'deskripsi' => 'Dalam berargumentasi, cenderung meminta bantuan teman atau pihak-pihak yang memiliki otoritas (ahli) dalam bidang tersebut.'],
            ['kode' => 'L069', 'deskripsi' => 'Senang terlibat dalam kegiatan sosial yang berkaitan dengan organisasi sekolah atau lingkungan tempat tinggal.'],
            ['kode' => 'L070', 'deskripsi' => 'Orang sering menunjuk sebagai pemimpin.'],
            ['kode' => 'L071', 'deskripsi' => 'Ketika sedang ada masalah, cenderung meminta bantuan kepada orang lain daripada berusaha menyelesaikan masalah itu sendirian.'],
            ['kode' => 'L072', 'deskripsi' => 'Lebih suka permainan untuk mengisi waktu luang dari pada hiburan bersifat individual seperti main game.'],
            ['kode' => 'L073', 'deskripsi' => 'Suka mengerjakan sesuatu sendirian tanpa ada gangguan orang lain.'],
            ['kode' => 'L074', 'deskripsi' => 'Memiliki buku harian atau catatan pribadi untuk menuliskan kehidupan pribadi.'],
            ['kode' => 'L075', 'deskripsi' => 'Mampu belajar dari kegagalan dan keberhasilan yang pernah di alami.'],
            ['kode' => 'L076', 'deskripsi' => 'Tidak suka keramaian.'],
            ['kode' => 'L077', 'deskripsi' => 'Tahu kelebihan dan kekurangan diri sendiri.'],
            ['kode' => 'L078', 'deskripsi' => 'Memiliki tekad yang kuat, mandiri dan berpendirian kuat (tidak mudah ikut-ikutan orang lain).'],
            ['kode' => 'L079', 'deskripsi' => 'Jika harus mengingat sesuatu, cenderung menutup mata dan merasakan situasi yang sedang terjadi.'],
            ['kode' => 'L080', 'deskripsi' => 'Lebih memilih menghabiskan akhir pekan sendirian dari pada menghabiskan waktu bersama teman.'],
            ['kode' => 'L081', 'deskripsi' => 'Jika sesuatu rusak dan tidak berfungsi, akan mempertimbangkan apakah benda tersebut layak untuk diperbaiki.'],
            ['kode' => 'L082', 'deskripsi' => 'Menganggap sebagai orang yang mandiri.'],
            ['kode' => 'L083', 'deskripsi' => 'Memiliki tujuan-tujuan penting dalam hidup, yang dipikirkan secara teratur.'],
            ['kode' => 'L084', 'deskripsi' => 'Memiliki hobi atau minat khusus yang disimpan untuk diri sendiri.'],
            ['kode' => 'L085', 'deskripsi' => 'Sangat memperhatikan sekeliling dan apa yang sedang terjadi di sekitar.'],
            ['kode' => 'L086', 'deskripsi' => 'Senang berjalan-jalan di hutan (atau taman) dan melihat-lihat pohon serta bunga.'],
            ['kode' => 'L087', 'deskripsi' => 'Senang berkebun.'],
            ['kode' => 'L088', 'deskripsi' => 'Mempunyai minat cukup besar pada alam, ekologi, tanaman atau binatang.'],
            ['kode' => 'L089', 'deskripsi' => 'Ketika dewasa, ingin pergi dari kota yang ramai ke tempat yang masih alamiah untuk menikmati alam.'],
            ['kode' => 'L090', 'deskripsi' => 'Suka berkelana, hiking, atau sekedar jalan-jalan di alam terbuka.'],
            ['kode' => 'L091', 'deskripsi' => 'Senang mempelajari nama-nama makhluk hidup di lingkungan, seperti bunga dan pohon.'],
            ['kode' => 'L092', 'deskripsi' => 'Dalam berargumentasi, cenderung membandingkan lawan seseorang atau sesuatu yang pernah dibaca atau dengar lalu bereaksi.'],
            ['kode' => 'L093', 'deskripsi' => 'Jika sesuatu rusak dan tidak berfungsi, akan memperhatikan sekeliling untuk melihat apa yang bisa ditemukan untuk memperbaikinya.'],
            ['kode' => 'L094', 'deskripsi' => 'Mampu mengerjakan dengan baik tugas / kegiatan yang berkaitan dengan sistem kehidupan (biologi, ilmu alam ).'],
            ['kode' => 'L095', 'deskripsi' => 'Cukup fasih menjelaskan perbedaan jenis pohon atau jenis flora dan fauna.'],
            ['kode' => 'L096', 'deskripsi' => 'Memiliki hewan peliharaan yang bermacam-macam atau setidaknya dua jenis hewan peliharaan dan mempunyai kebun.'],
            ['kode' => 'L097', 'deskripsi' => 'Menyukai pembahasan tentang kehidupan.'],
            ['kode' => 'L098', 'deskripsi' => 'Agama adalah hal yang penting.'],
            ['kode' => 'L099', 'deskripsi' => 'Menikmati jika melihat karya seni.'],
            ['kode' => 'L100', 'deskripsi' => 'Relaksasi dan meditasi latihan yang bermanfaat.'],
            ['kode' => 'L101', 'deskripsi' => 'Suka mengunjungi situs alam.'],
            ['kode' => 'L102', 'deskripsi' => 'Menikmati membaca filsuf kuno dan modern.'],
            ['kode' => 'L103', 'deskripsi' => 'Belajar hal-hal baru lebih mudah ketika memahaminya.'],
            ['kode' => 'L104', 'deskripsi' => 'Ingin mengetahui apakah ada bentuk-bentuk lain dari kehidupan di alam semesta.'],
            ['kode' => 'L105', 'deskripsi' => 'Mempelajari sejarah dan budaya kuno membantu memberi suatu pandangan yang nyata.'],
            ['kode' => 'L106', 'deskripsi' => 'Hobi membaca buku sejarah.'],
            ['kode' => 'L107', 'deskripsi' => 'Cukup Fasih dalam menjelaskan budaya kuno.'],
            ['kode' => 'L108', 'deskripsi' => 'Mempunyai minat cukup besar dalam mempelajari sejarah.'],
        ];

        foreach ($ciriCiri as $item) {
            CiriCiri::create($item);
        }
    }
}